#!/bin/bash

# Required packages: pipewire pamixer pulseaudio-utils

AUDIO_HIGH_SYMBOL=' '
AUDIO_MED_HIGH_THRESH=70
AUDIO_MED_HIGH_SYMBOL=' '
AUDIO_MED_THRESH=30
AUDIO_MED_SYMBOL=' '
AUDIO_LOW_THRESH=0
AUDIO_LOW_SYMBOL=' '
AUDIO_MUTED_SYMBOL=' '
AUDIO_INTERVAL=1
DEFAULT_COLOR="#9ADA9A"
MUTED_COLOR="#FF0000"
LONG_FORMAT=1
SHORT_FORMAT=0
USE_PERCENT=1
USE_ALSA_NAME=0
USE_DESCRIPTION=1

while getopts "F:f:pdH:M:L:X:T:t:C:c:i:h" opt; do
  case "$opt" in
    F) LONG_FORMAT="$OPTARG" ;;
    f) SHORT_FORMAT="$OPTARG" ;;
    p) USE_PERCENT=0 ;;
    d) USE_DESCRIPTION=1 ;;
    H) AUDIO_HIGH_SYMBOL="$OPTARG" ;;
    M) AUDIO_MED_SYMBOL="$OPTARG" ;;
    L) AUDIO_LOW_SYMBOL="$OPTARG" ;;
    X) AUDIO_MUTED_SYMBOL="$OPTARG" ;;
    T) AUDIO_MED_THRESH="$OPTARG" ;;
    t) AUDIO_LOW_THRESH="$OPTARG" ;;
    C) DEFAULT_COLOR="$OPTARG" ;;
    c) MUTED_COLOR="$OPTARG" ;;
    i) AUDIO_INTERVAL="$OPTARG" ;;
    h) printf "help" ;;
  esac
done

function print_block {
  DEFAULT_SINK=$(pactl info | grep 'Default Sink' | awk '{print $3}')
  DESCRIPTION=$(pactl list sinks | awk '/Description/ {gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}')
  INDEX=$(pactl list sinks | awk -v DS="$DEFAULT_SINK" '/Sink #/ {gsub(/^[ \t]+|[ \t]+$/, "", $2)} $2 == DS {getline; print $2}')
  NAME=$DESCRIPTION
  [[ $USE_PERCENT == 1 ]] && VOL=$(pamixer --get-volume) || VOL=$(pamixer --get-volume-human)
  MUTED=$(pamixer --get-mute)

  SYMBOL=$AUDIO_HIGH_SYMBOL
  COLOR=$DEFAULT_COLOR

  if [[ $MUTED == "true" ]]; then
    SYMBOL=$AUDIO_MUTED_SYMBOL
    COLOR=$MUTED_COLOR
  elif [[ ${VOL%\%} -le $AUDIO_MED_HIGH_THRESH ]]; then
    SYMBOL=$AUDIO_MED_HIGH_SYMBOL
  elif [[ ${VOL%\%} -le $AUDIO_MED_THRESH ]]; then
    SYMBOL=$AUDIO_MED_SYMBOL
  elif [[ ${VOL%\%} -le $AUDIO_LOW_THRESH ]]; then
    SYMBOL=$AUDIO_LOW_SYMBOL
  fi

  echo "$SYMBOL$VOL [$INDEX:$NAME]"
  echo "$SYMBOL$VOL [$DESCRIPTION]"
  echo "$COLOR"
}

print_block

# Left-click handling: Open pavucontrol on left-click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  dunstify -t 1675 -h string:fgcolor:#FFFFFF -h string:bgcolor:#882223 "Audio Settings" && pavucontrol
fi
