#!/bin/sh

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

# full text
echo "$load"

# short text
echo "$load"

# color if load is too high
awk -v cpus="$cpus -v cpuload="$load '
    BEGIN {
        if (cpus <= cpuload) {
            print "#FF0000";
            exit 33;
        }
    }
'

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
      dunstify -t 1675 -h string:fgcolor:#000000 -h string:bgcolor:#00FF00 "POWERTOP" && alacritty -e sudo powertop --auto-tune
fi
