#!/bin/bash
# It is a basic bash script to set a simple alarm, based on the interval set by the user's input.
# It depends on bash

echo "Choose an interval (in minutes) for your alarm:";
read chosenInterval;
interval=$((chosenInterval*60))
clear

progress_bar()
{
  local DURATION=$1
  local INT=0.25      # refresh interval

  local TIME=0
  local CURLEN=0
  local SECS=0
  local FRACTION=0

  local FB=2588       # full block

  trap "echo -e $(tput cnorm); trap - SIGINT; return" SIGINT

  echo -ne "$(tput civis)\r$(tput el)│"                # clean line

  local START=$( date +%s%N )

  while [ $SECS -lt $DURATION ]; do
    local COLS=$( tput cols )

    # main bar
    local L=$( bc -l <<< "( ( $COLS - 5 ) * $TIME  ) / ($DURATION-$INT)" | awk '{ printf "%f", $0 }' )
    local N=$( bc -l <<< $L                                              | awk '{ printf "%d", $0 }' )

    [ $FRACTION -ne 0 ] && echo -ne "$( tput cub 1 )"  # erase partial block

    if [ $N -gt $CURLEN ]; then
      for i in $( seq 1 $(( N - CURLEN )) ); do
        echo -ne \\u$FB
      done
      CURLEN=$N
    fi

    # partial block adjustment
    FRACTION=$( bc -l <<< "( $L - $N ) * 8" | awk '{ printf "%.0f", $0 }' )

    if [ $FRACTION -ne 0 ]; then
      local PB=$( printf %x $(( 0x258F - FRACTION + 1 )) )
      echo -ne \\u$PB
    fi

    # percentage progress
    local PROGRESS=$( bc -l <<< "( 100 * $TIME ) / ($DURATION-$INT)" | awk '{ printf "%.0f", $0 }' )
    echo -ne "$( tput sc )"                            # save pos
    echo -ne "\r$( tput cuf $(( COLS - 6 )) )"         # move cur
    echo -ne "│ $PROGRESS%"
    echo -ne "$( tput rc )"                            # restore pos

    TIME=$( bc -l <<< "$TIME + $INT" | awk '{ printf "%f", $0 }' )
    SECS=$( bc -l <<<  $TIME         | awk '{ printf "%d", $0 }' )

    # take into account loop execution time
    local END=$( date +%s%N )
    local DELTA=$( bc -l <<< "$INT - ( $END - $START )/1000000000" \
                   | awk '{ if ( $0 > 0 ) printf "%f", $0; else print "0" }' )
    sleep $DELTA
    START=$( date +%s%N )
  done

  echo $(tput cnorm)
  trap - SIGINT
}

progress_bar $interval

for (( ; ; ))
do
  dunstify -t 5000 -h string:fgcolor:#000000 -h string:bgcolor:#FF0013 "TIME TO QUIT":
  espeak "Stop please. It's time to shut down"
  sleep 10
done

# Prompt the user for the time interval and volume inputs
read -p "Enter the time interval (hh.mm.ss format): " interval_input
read -p "Enter the volume (0.0-1.0): " volume_input

# Calculate the sleep time based on the time interval
IFS='.' read -ra time_parts <<< "$interval_input"
seconds=$((${time_parts[0]} * 3600 + ${time_parts[1]} * 60 + ${time_parts[2]}))
sleep_time=$(bc -l <<< "$seconds / 100")

# Create a new progress bar
bar_width=20
echo "Timer $interval_input :"
for ((x = 1; x <= 100; x++)); do
  bar_length=$(bc -l <<< "$bar_width * $x / 100")
  printf "\r%-$bar_width.${bar_length}s" "===================="
  sleep "$sleep_time"
done

echo -e "\nTime's up."

# Play the alert sound
alert_file="sounds/alert.wav"
aplay "$alert_file" -q &

# Adjust the volume of the alert sound
amixer -q sset Master "$volume_input"

# Wait for the alert sound to finish playing
sleep 5
