#!/bin/sh
#It is a basic bash script to interact with ffmpeg (very few options added by now)
#It depends on bash zenity ffmpeg

################################ FUNCTIONS ################################

sel_vid_format() {
  option=$(zenity --list --title "Video Format" --text "Select a video format:" \
  --column "MEDIA FORMAT:" "mp3" "flac" "wav" "opus" "mp4" "mkv" "avi" \
  --hide-header --width=820 --height=460 --ok-label="OK" --cancel-label="Cancel")
  case $option in
    "mp3")
      export V_FORMAT="mp3"
      ;;
    "flac")
      export V_FORMAT="flac"
      ;;
    "wav")
      export V_FORMAT="wav"
      ;;
    "opus")
      export V_FORMAT="opus"
      ;;
    "mp4")
      export V_FORMAT="mp4"
      ;;
    "mkv")
      export V_FORMAT="mkv"
      ;;
    "avi")
      export V_FORMAT="avi"
      ;;
  esac
}

sel_img_format() {
  option=$(zenity --list --title "Image Format" --text "Select an image format:" \
  --column "MEDIA FORMAT:" "jpg" "jpeg" "tiff" "png" "gif" "webp" "avif" \
  --hide-header --width=820 --height=460 --ok-label="OK" --cancel-label="Cancel")
  case $option in
    "jpg")
      export I_FORMAT="jpg"
      ;;
    "jpeg")
      export I_FORMAT="jpeg"
      ;;
      "tiff")
      export I_FORMAT="tiff"
      ;;
    "png")
      export I_FORMAT="png"
      ;;
    "gif")
      export I_FORMAT="gif"
      ;;
    "webp")
      export I_FORMAT="webp"
      ;;
    "avif")
      export I_FORMAT="avif"
      ;;
  esac
}

sel_width() {
  WIDTH=$(zenity --entry --title "Enter the desired width:" --text "Enter the desired width for the image")
  export WIDTH
}

sel_height() {
  HEIGHT=$(zenity --entry --title "Enter the desired height:" --text "Enter the desired height for the image")
  export HEIGHT
}

sel_dimensions() {
  option=$(zenity --list --title "Image Format" --text "Specify the desired dimensions:" \
    --column "Aspect Ratio" "2048 X 1080 (16:9)" "1920 X 1080 (16:9)" "1024 X 576 (4:3)" "800 X 450 (16:3)" \
    "2048 X 1536 (4:3)" "1152 X 864 (4:3)" "1024 X 864 (4:3)" "800 X 600 (4:3)" "Custom" \
  --width=300 --height=460 --ok-label="OK" --cancel-label="Cancel")
  case $option in
    "2048 X 1080 (16:9)")
      export SCALE="2048:1080"
      ;;
    "1920 X 1080 (16:9)")
      export SCALE="1920:1080"
      ;;
    "1024 X 576i (4:3)")
      export SCALE="1024:576"
      ;;
    "800x450 (16:3)")
      export SCALE="800:450"
      ;;
    "2048 X 1536 (4:3)")
      export SCALE="2048:1536"
      ;;
    "1152 X 864 (4:3)")
      export SCALE="1152:864"
      ;;
    "1024 X 864i (4:3)")
      export SCALE="1024:864"
      ;;
    "800 X 600i (4:3)")
      export SCALE="800:600"
      ;;
    "Custom")
      sel_width
      sel_height
      ;;
  esac
}

sel_framerate() {
  FPS=$(zenity --entry --title "Enter the framerate" --text "Enter the desired framerate:")
  [[ "$FPS" ]] || exit 1
}

sel_file() {
  files=$(zenity --title "Select a one or more files:"  --file-selection --multiple --filename=$(pwd)/)
  [[ "$files" ]] || exit 1
  echo $files | tr "|" "\n" | while read file
  do
    echo "$file" >> /tmp/files.txt
  done
}

sel_dir() {
  dir=$(zenity --file-selection --directory)
  export DIR=$dir
}

video_conv() {
  WORK_DIR=$(pwd)/CONVERTED/
  FILES_LIST=/tmp/files.txt
  sel_file
  sel_vid_format
  mkdir -p $WORK_DIR
  IFS=$'\n'
  for FILE in $(cat $FILES_LIST);
  do
    FILENAME=`basename "${FILE}"`
    OUTPUT_FILE="$WORK_DIR${FILENAME%.*}.$V_FORMAT"
    ffmpeg -i "$FILE" -c:v libx264 -pix_fmt yuv420p "$OUTPUT_FILE";
  done
  rm files.txt
  rm $FILES_LIST
  echo "Temporary files removed!"
}

image_conv() {
  WORK_DIR=$(pwd)/CONVERTED/
  FILES_LIST=/tmp/files.txt
  sel_file
  sel_img_format
  mkdir -p $WORK_DIR
  IFS=$'\n'
  for FILE in $(cat "$FILES_LIST"); do
    FILENAME=$(basename "$FILE")
    OUTPUT_FILE="$WORK_DIR${FILENAME%.*}.$I_FORMAT"
    echo "Converting $FILENAME to $OUTPUT_FILE"
    ffmpeg -i "$FILE" "$OUTPUT_FILE"
  done
  rm "$FILES_LIST"
  echo "Temporary files removed!"
}

img_vid() {
  sel_dir
  sel_img_format
  sel_vid_format
  sel_framerate
  GLOB_PATTERN="*.$I_FORMAT"
  OUTPUT_DIR=$(pwd)/VIDEOS/
  mkdir -p $OUTPUT_DIR
  OUTPUT_FILE="$OUTPUT_DIR$(date +%Y%m%d-%H%M%S).$V_FORMAT"
  cd $DIR
  ffmpeg -framerate $FPS -pattern_type glob -i "$GLOB_PATTERN" -c:a copy -shortest -c:v libx264 -pix_fmt yuv420p "$OUTPUT_FILE"
  rm $FILES_LIST
  echo ""
  echo "Temporary files removed!"
}

scale() {
  WORK_DIR=$(pwd)/SCALED/
  FILES_LIST=/tmp/files.txt
  sel_file
  sel_img_format
  sel_dimensions
  mkdir -p "$WORK_DIR"
  for FILE in $(cat "$FILES_LIST"); do
    FILENAME=$(basename "$FILE")
    FILENAME_NOEXT="${FILENAME%.*}" # Remove file extension
    SCALED_FILE="${WORK_DIR}${FILENAME_NOEXT}_scaled.${I_FORMAT}"
    echo "Scaling $FILE to $SCALED_FILE"
    ffmpeg -i "$FILE" -vf "scale=${SCALE}" "$SCALED_FILE"
    CONVERTED_FILE="${WORK_DIR}${FILENAME_NOEXT}_converted.${V_FORMAT}"
    echo "Converting $SCALED_FILE to $CONVERTED_FILE"
    ffmpeg -i "$SCALED_FILE" "$CONVERTED_FILE"
  done
  rm "$FILES_LIST"
  echo "Temporary files removed!"
  echo "Done!"
}

scale_and_crop() {
  input_image=$(zenity --file-selection --title "Select an input image:")
  [ -z "$input_image" ] && return
  desired_dimensions=$(zenity --forms --title="Enter Dimensions and Aspect Ratio:" --text="Enter the desired dimensions and aspect ratio:" \
    --add-entry="Width" --add-entry="Height" --add-entry="Aspect Ratio (e.g., 16:9)" --width=500 --height=200)
  if [ -z "$desired_dimensions" ]; then
    return
  fi
  IFS='|' read -r width height aspect_ratio <<< "$desired_dimensions"
  output_image=$(zenity --file-selection --save --confirm-overwrite --title "Save As" --file-filter="Image files (png jpg jpeg gif bmp tiff tif)")
  [ -z "$output_image" ] && return
  ffmpeg -i "$input_image" -vf "scale=$width:$height,crop=$width:$height" "$output_image"
}

frames() {
  WORK_DIR=$(pwd)/FRAMES/
  FILES_LIST=/tmp/files.txt
  sel_file
  sel_img_format
  sel_framerate
  mkdir -p $WORK_DIR
  IFS=$'\n'
  for FILE in $(cat $FILES_LIST);
  do
    FILE_NAME=$(basename "$FILE")
    OUTPUT_FILE="$WORK_DIR/frame_%05d.${I_FORMAT}"
    ffmpeg -i "$FILE" -r $FPS -f image2 "$OUTPUT_FILE"
    echo "Created $WORK_DIR/frame_%05d.${I_FORMAT}"
  done
  rm $FILES_LIST
  echo "Temporary files removed!"
}

get_framerate() {
  sel_file
  FILE_NAME_WITH_BACKSLASH=""
  FILES_LIST=/tmp/files.txt
  IFS=$'\n'
  for FILE in $(cat $FILES_LIST); do
    FILE_NAME=$(basename "$FILE")
    FILE_FPS=$(ffmpeg -i "$FILE" 2>&1 | sed -n "s/.*, \(.*\) fp.*/\1/p")
    FILE_NAME_WITH_BACKSLASH=$(echo "$FILE_NAME" | sed 's/ /\\ /g')
    echo ""
    echo "The original framerate of $FILE_NAME_WITH_BACKSLASH is $FILE_FPS fps"
    echo ""
  done
  rm $FILES_LIST
  echo "Temporary files removed!"
}

sel_action() {
  option=$(zenity --list --title "FFMPEG Converter" --text "Select an action to perform:" \
  --column "ACTIONS:" "Video Converter" "Image Converter" "Scale Images" "Scale and Crop" \
   "Images to video" "Video to frames" "Detect framerate" \
  --hide-header --width=275 --height=350 --ok-label="OK" --cancel-label="Cancel")
  case $option in
    "Video Converter")
      video_conv
      ;;
    "Image Converter")
      image_conv
      ;;
    "Scale Images")
      scale
      ;;
    "Scale and Crop")
      scale_and_crop
      ;;
    "Images to video")
      img_vid
      ;;
    "Video to frames")
      frames
      ;;
    "Detect framerate")
      get_framerate
      ;;
  esac
}

sel_action
