#!/bin/sh
#It is a simple bash script to interact with yt-dlp (https://github.com/yt-dlp/yt-dlp)
#It depends on: bash zenity yt-dlp

################################ FUNCTIONS ################################

ListActions() {
  option=$(zenity --list --title "Video Downloader" --text "Select an action to perform:" \
  --column "ACTIONS:" "Download a video" "Extract the audio from a video" \
  "Download video playlist" "Download audio playlist" \
  --hide-header --width=750 --height=460 --ok-label="OK" --cancel-label="Cancel")
  case $option in
    "Download a video")
      echo "You chose to download a video"
      export ACTION="download"
      ;;
    "Extract the audio from a video")
      echo "You chose to extract the audio from a video"
      export ACTION="extract"
      ;;
    "Download video playlist")
      echo "You chose to download a video playlist"
      export ACTION="v_playlist"
      ;;
    "Download audio playlist")
      echo "You chose to download an audio playlist"
      export ACTION="a_playlist"
      ;;
      esac
}

InsertURL() {
  echo ""
  echo "Paste a media URL:"
  read -r URL
  # Export the user_input variable
  export URL
}

SelectFile() {
  files=$(zenity --file-selection --multiple --filename=$HOME/)
  [[ "$files" ]] || exit 1
  echo $files | tr "|" "\n" | while read file
  do
    echo "$file" >> files.txt
  done
}

################################## SCRIPT ##################################

ListActions

if [ "$ACTION" = "download" ]; then
  echo ""
  echo "VIDEO DOWNLOADER"
  InsertURL
  echo "Searching for available formats..."
  echo "Downloading..."
  yt-dlp -o "Media/$(date +%Y%m%d-%H%M%S)-%(title)s" -i --hls-prefer-ffmpeg --print-traffic "$URL" --lazy-playlist
  echo "Done!"
fi
if [ "$ACTION" = "extract" ]; then
  echo ""
  echo "AUDIO EXTRACTOR"
  InsertURL
  yt-dlp --audio-quality "ba" -x "$URL" -o "Media/$(date +%Y%m%d-%H%M%S)-%(title)s.%(ext)s"
  echo "Done!"
fi
if [ "$ACTION" = "v_playlist" ]; then
  echo ""
  echo "VIDEO PLAYLIST DOWNLOADER"
  InsertURL
  yt-dlp -f 'bv*[height=1080]+ba' "$URL" -o 'VideoPlaylist/$(date "%H%M%S")-%(title)s.%(ext)s'
  echo "Downloading..."
  echo "Done!"
fi
if [ "$ACTION" = "a_playlist" ]; then
  echo ""
  echo "AUDIO PLAYLIST DOWNLOADER"
  InsertURL
  yt-dlp --audio-quality "ba" -x "$URL" -o 'AudioPlaylist/$(date +%Y%m%d-%H%M%S)-%(title)s.%(ext)s'
  echo "Downloading..."
  echo "Done!"
fi
