#!/bin/sh



SelectDirectory() {
  dir=$(zenity --title "Select the directory containing the images:"  --file-selection --directory --filename=$HOME/.virtualenv/comfyUI/I:\AI\output\ComfyUI)
  export dir=$dir
}

SelectFramerate() {
  read -p "Enter the framerate: " FRAME
  export framerate=$FRAME
}

SelectFormat() {
   format=$(zenity --list --text "Choose the video framerate:" \
    --column "Image Format" --width=820 --height=460 --hide-header \
    "JPG" "PNG" "TIFF" "gif" "webp" "avif")
  case $format in
    "JPG")
      export IMAGE_FORMAT='*.jpg'
      ;;
    "PNG")
      export IMAGE_FORMAT='*.png'
      ;;
    "TIFF")
      export IMAGE_FORMAT='*.tiff'
      ;;
    "gif")
      export IMAGE_FORMAT='*.gif'
      ;;
    "webp")
      export IMAGE_FORMAT='*.webp'
      ;;
    "avif")
      export IMAGE_FORMAT='*.avif'
      ;;
  esac
}

SelectFile() {
  files=$(zenity --file-selection --multiple --filename=$(pwd)/)
  [[ "$files" ]] || exit 1
  echo $files | tr "|" "\n" | while read file
  do
    echo "$file" >> files.txt
  done
}

SelectDirectory
SelectFramerate

cd $dir && ffmpeg -framerate $FRAME -pattern_type glob -i '*.jpg' -c:a copy -shortest -c:v libx265 -pix_fmt yuv420p $(date +"%m-%d-%y_%H-%M-%S").mp4
