#!/bin/sh
#This script is used to launch other scripts.
#It depends on bash zenity

################################ FUNCTIONS ################################

WORKDIR=$HOME/.scripts

ListActions() {
  CHOICE=$(zenity --list --text "Select an action to perform:" \
    --column "SCRIPTS" "Alarm" "Whisper" "Realtime Transcription" "Tesseract OCR" \
             "Translator" "Downloader" "Converter" \
             "Polymath" "TTS" "ComfyUI" "Riffusion"\
             "Background Remover" "Images into video" \
             "Remove Duplicates" "Activate Virtualenv" \
    --width=820 --height=480\
    --ok-label "OK" --cancel-label "Cancel" \
)
  case $CHOICE in
    "Alarm")
      SCRIPT="alarm.sh"
      ;;
    "Whisper")
      SCRIPT="whisper.sh"
      ;;
    "Realtime Transcription")
      SCRIPT="realtimeWhisper.sh"
      ;;
    "Tesseract OCR")
      SCRIPT="tesseract.sh"
      ;;
    "Translator")
      SCRIPT="argos.sh"
      ;;
    "Downloader")
      SCRIPT="downloader.sh"
      ;;
    "Converter")
      SCRIPT="converter.sh"
      ;;
    "Polymath")
      SCRIPT="polymath.sh"
      ;;
    "TTS")
      SCRIPT="tts.sh"
      ;;
    "ComfyUI")
      SCRIPT="comfyUI.sh"
      ;;
    "Riffusion")
      SCRIPT="riffusion.sh"
      ;;
    "Background Remover")
      SCRIPT="bgRemover.sh"
      ;;
    "Images into video")
      SCRIPT="img2vid.sh"
      ;;
    "Remove Duplicates")
      SCRIPT="rmDuplicate.sh"
      ;;
    "Activate Virtualenv")
      SCRIPT="vactivate.sh"
      ;;
  esac
  # Export the user's input variable
  export SCRIPT
}

################################## SCRIPT ##################################

ListActions
echo""
sh $WORKDIR/$SCRIPT
