#!/bin/sh
#Simple script to launch Stable-Diffusion_Webui in a virtualenv
#It depends on: bash virtualenv stable-diffusion-webui (https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki)

WORKDIR=$HOME/.virtualenv/stablediffusion

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WORKDIR/lib/python3.9/site-packages/

ProgressBar() {
  TOTAL=40
  INTERVAL=1
  echo "This may take a while..."
  echo ""
  echo "Please be patient while Stable Diffusion backend is being initialized."
  echo ""
  start=`date +%s`
  while [ $INTERVAL -lt $TOTAL ]; do
    sleep 0.2
    cur=`date +%s`
    INTERVAL=$(( $INTERVAL + 1 ))
    pd=$(( $INTERVAL * 73 / $TOTAL ))
    runtime=$(( $cur-$start ))
    estremain=$(( ($runtime * $TOTAL / $INTERVAL)-$runtime ))
    printf "\r%d.%d%% complete ($INTERVAL of $TOTAL) - est %d:%0.2d remaining\e[K" $(( $INTERVAL*100/$TOTAL )) $(( ($INTERVAL*1000/$TOTAL)%10)) $(( $estremain/60 )) $(( $estremain%60 ))
  done
  echo ""
  printf "\nLaunching Stable Diffusion...\n"
}

Launch() {
    cd $WORKDIR
    ProgressBar
    source bin/activate
    python $WORKDIR/launch.py --xformers --api --medvram --update-all-extensions --autolaunch --allow-code
}

SDWebUI() {
  ProgressBar && firefox http://127.0.0.1:7860/
}

Launch
