#!/usr/bin/env bash

# Configuration section: Customize these variables as needed
FG_COLOR="${FG_COLOR:-#bbbbbb}"           # Foreground color
BG_COLOR="${BG_COLOR:-#90ee90}"           # Background color
HLFG_COLOR="${HLFG_COLOR:-#111111}"       # Highlighted foreground color
HLBG_COLOR="${HLBG_COLOR:-#90ee90}"       # Highlighted background color
BORDER_COLOR="${BORDER_COLOR:-#222222}"   # Border color
TITLE="${TITLE:-Menu}"                    # Yad dialog title
TEXT="${TEXT:-Action:}"                   # Yad dialog text
OPTIONS=(${OPTIONS:---column= --hide-header})  # Yad dialog options
enable_confirmation=${ENABLE_CONFIRMATIONS:-false}  # Enable user confirmation

# Function to check if a command exists
command_exists() {
  command -v "$1" &> /dev/null 2>&1
}

# Check if systemctl command is available, required for some operations
if ! command_exists systemctl; then
  exit 1
fi

# Associative array to define menu items and their corresponding commands
declare -A menu
menu=(
  [Shutdown]="systemctl poweroff"
  [Reboot]="systemctl reboot"
  [Hibernate]="systemctl hibernate"
  [Logout]="i3-msg exit"
)

# Number of menu items
menu_nrows=${#menu[@]}

# Menu entries that require confirmation
menu_confirm="Shutdown Reboot Hibernate Suspend Halt Logout"

# Function to ask for user confirmation using Yad
ask_confirmation() {
  yad --question --text "Are you sure you want to ${selection,,}?"
  confirmed=$?
  if [ "${confirmed}" == 0 ]; then
    i3-msg -q "exec ${menu[${selection}]}"
  fi
}

# Set Yad as the menu launcher
launcher_exe="yad"
launcher_options=(--list --title="${TITLE}" --text="${TEXT}" "${OPTIONS[@]}")

launcher=(${launcher_exe} "${launcher_options[@]}")

# Display the menu and get the user's selection
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"

# Process the user's selection
if [[ $? -eq 0 && ! -z ${selection} ]]; then
  if [[ "${enable_confirmation}" = true && \
        ${menu_confirm} =~ (^|[[:space:]])"${selection}"($|[[:space:]]) ]]; then
    ask_confirmation
  else
    i3-msg -q "exec ${menu[${selection}]}"
  fi
fi
